const NAMESPACE = 'clothing/shop:';

export default {
    FETCH_COLLECTIONS: `${NAMESPACE}FETCH_COLLECTIONS`,
    FETCH_COLLECTIONS_INIT: `${NAMESPACE}FETCH_COLLECTIONS_INIT`,
    FETCH_COLLECTIONS_SUCCESS: `${NAMESPACE}FETCH_COLLECTIONS_SUCCESS`,
    FETCH_COLLECTIONS_FAILLURE: `${NAMESPACE}FETCH_COLLECTIONS_FAILLURE`,
}