const NAMESPACE = 'clothing/user:';

export default {
    // SIGNIN_INIT: `${NAMESPACE}SIGNIN_INIT`,
    SIGNIN: `${NAMESPACE}SIGNIN`,
    SIGN_IN_SUCCESS: `${NAMESPACE}SIGN_IN_SUCCESS`,
    SIGN_IN_FAILURE: `${NAMESPACE}SIGN_IN_FAILURE`,

    SIGNIN_WITH_GOOGLE: `${NAMESPACE}SIGNIN_WITH_GOOGLE`,
    SIGNIN_WITH_GOOGLE_SUCCESS: `${NAMESPACE}SIGNIN_WITH_GOOGLE_SUCCESS`,

    SIGNUP: `${NAMESPACE}SIGNUP`,

    SIGN_OUT: `${NAMESPACE}SIGN_OUT`,
    SIGN_OUT_SUCCESS: `${NAMESPACE}SIGN_OUT_SUCCESS`,
    
    CHECK_USER_SESSION: `${NAMESPACE}CHECK_USER_SESSION`,
    
}