const NAMESPACE = 'clothing/cart:';
export default {
    ADD_ITEM: `${NAMESPACE}ADD_ITEM`,
    REMOVE_ITEM: `${NAMESPACE}REMOVE_ITEM`,
    CLEAR_ITEM: `${NAMESPACE}CLEAR_ITEM`,
    CLEAR_CART: `${NAMESPACE}CLEAR_CART`,
}